[package]
name = "durable-evals-server"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "durable-eval"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
durable-evals-core.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
